export const extrasData = [
    {
        type: "trailer",
        number: 1,
        title: "Season 1 - Trailer",
        thumbnail: "t01.avif",
        description: "The King’s jester, Jestro, has gone rogue and stolen the strange talking Book of Monsters. No place is safe. Jestro, the Book and its monsters are on the loose, causing havoc all over the kingdom. Dark secrets from the past start to reveal themselves in the deep memory of holographic wizard Merlok 2.0 as it becomes unclear who the real enemy mastermind is: Jestro or the Book of Monsters? It’s up to the brave NEXO Knights to come to the rescue.",
        metadata: "1m · Jan 30, 2015",
        scheme_metadata: "duration=PT1M|download=T01 - Season 1.mp4",
        video_data: ["720p", "English", "None"],
        capture_time: "0:27",
        link: "episode.html?trailer=1",
        mp4_link: "T01 - Season 1.mp4"
    },
    {
        type: "trailer",
        number: 2,
        title: "Season 2 - Trailer",
        thumbnail: "t02.avif",
        description: "The stakes couldn't be higher as Knighton remains under siege by Jestro, the Book and their monsters. In their relentless search for the lost magical Books, the villains are growing more powerful and it will only be a matter of time before they can conquer the entire kingdom. Can the NEXO Knights, now an efficient monster-fighting unit, stop their evil plans? This action-packed Second Season takes our five heroes on a wild ride in pursuit of their adversaries... from a glitzy golden gala to a crazy comic book convention to a spicy chili cook-off. There's even a trip back to school for the Knights to upgrade their equipment and NEXO powers to keep up with the ever-growing threat. But will that be enough to save Knighton?",
        metadata: "1m · May 30, 2016",
        scheme_metadata: "duration=PT1M10S|download=T02 - Season 2.mp4",
        video_data: ["720p", "English", "None"],
        capture_time: "0:13",
        link: "episode.html?trailer=2",
        mp4_link: "T02 - Season 2.mp4"
    },
    {
        type: "trailer",
        number: 3,
        title: "Season 3 - Trailer",
        thumbnail: "t03.avif",
        description: "A storm is brewing over Knighton! A diabolical cloud (the Cloud of Monstrox) has reteamed with Jestro for a new scheme to destroy the kingdom. This time he’s raising an army of lightning-infused stone monsters to collect all of the sector’s Forbidden Powers. Once they are combined, Monstrox will have the power to bring the Stone Colossus of Ultimate Destruction to life, giving him indestructible power. But don’t count out our heroic Knights. With advanced battle suits and the newly discovered force of combining NEXO Powers, the Knights may have the edge. However, the situation grows dire when Clay discovers he’s gradually turning to stone! Can Merlok 2.0 find a way to save Clay in time… or will another Knight be chosen to lead our fearless team?",
        metadata: "1m · Dec 19, 2016",
        scheme_metadata: "duration=PT30S|download=T03 - Season 3.mp4",
        video_data: ["720p", "Dutch", "None"],
        capture_time: "0:09",
        link: "episode.html?trailer=3",
        mp4_link: "T03 - Season 3.mp4"
    },
    {
        type: "trailer",
        number: 4,
        title: "Season 4 - Trailer",
        thumbnail: "t04.avif",
        description: "The NEXO Knights band together and fight for their Kingdom. Jestro and the Monstrox find the final six Forbidden Powers and bring the STONE COLOSSUS to life. It marches across the realm destroying everything in its path. Will the NEXO Knights defeat the Colossus, destroy Monstrox, capture Jestro and restore peace for Knighton?",
        metadata: "1m · Aug 8, 2017",
        scheme_metadata: "duration=PT1M10S|download=T04 - Season 4.mp4",
        video_data: ["720p", "Ukranian", "None"],
        capture_time: "0:06",
        link: "episode.html?trailer=4",
        mp4_link: "T04 - Season 4.mp4"
    },
    {
    	type: "trailer",
        number: 5,
        title: "Clay - Trailer",
        thumbnail: "t05.avif",
        description: "It is not easy to be a knight and pull an enchanted sword out of a stone. Especially when the Nexo Knight Clay Morrington comes by to ‘help’. With his super-powered, high-tech armor and sword, it is an easy job for Clay, but the hopelessly ordinary knight might feel a bit outdated.",
        metadata: "1m · Oct 8, 2015",
        scheme_metadata: "duration=PT30S|download=T05 - Clay.mp4",
        video_data: ["720p", "English", "None"],        
        capture_time: "0:14",  
        link: "episode.html?trailer=5",
        mp4_link: "T05 - Clay.mp4"      
    },   
    {
    	type: "trailer",
        number: 6,
        title: "Lance - Trailer",
        thumbnail: "t06.avif",
        description: "Poor ordinary knights. Two of them are fighting over a beautiful lady, but none of them have the skill for victory. In slides the shiny Nexo Knight Lance in his techno armor, riding on his amazing, gleaming hover steed. He throws a single smile at the lady and rides of with her into the sunset.",
        metadata: "1m · Oct 8, 2015",
        scheme_metadata: "duration=PT36S|download=T06 - Lance.mp4",
        video_data: ["720p", "English", "None"],        
        capture_time: "0:03",  
        link: "episode.html?trailer=6",
        mp4_link: "T06 - Lance.mp4"      
    },       
    {
    	type: "trailer",
        number: 7,
        title: "Macy - Trailer",
        thumbnail: "t07.avif",
        description: "The sleeping beauty Macy is woken up by her digital alarm clock. She starts doing ordinary girl-getting-up stuff, but there is nothing ordinary about this girl. She doesn’t put on a dress, she puts on an armor. Macy is a Nexo Knight! She grabs her power mace and takes a few swings with near accidental consequences.",
        metadata: "1m · Oct 8, 2015",
        scheme_metadata: "duration=PT36S|download=T07 - Macy.mp4",
        video_data: ["720p", "English", "None"],        
        capture_time: "0:02",  
        link: "episode.html?trailer=7",
        mp4_link: "T07 - Macy.mp4"      
    },      
    {
    	type: "trailer",
        number: 8,
        title: "Aaron - Trailer",
        thumbnail: "t08.avif",
        description: "Nexo Knights make even Robin Hood feel old. When he finally gets the bulls-eye he has been aiming at, Robin is overjoyed. But it doesn’t last long. The Nexo Knight Aaron flies in on his incredible hover shield and with one shot of his high-powered laser blaster he shows Robin how a true marksman makes his mark.",
        metadata: "1m · Oct 8, 2015",
        scheme_metadata: "duration=PT36S|download=T08 - Aaron.mp4",
        video_data: ["720p", "English", "None"],        
        capture_time: "0:13",  
        link: "episode.html?trailer=8",
        mp4_link: "T08 - Aaron.mp4"      
    },   
     {
    	type: "trailer",
        number: 9,
        title: "Axl - Trailer",
        thumbnail: "t09.avif",
        description: "A boy flees down a beanstalk and tries to cut it down with a big axe. Axl comes by and with a single chop the helpful, hungry giant brings the beanstalk down. The boys troubles are solved. For a short while…",
        metadata: "1m · Oct 8, 2015",
        scheme_metadata: "duration=PT36S|download=T09 - Axl.mp4",
        video_data: ["720p", "English", "None"],        
        capture_time: "0:12",  
        link: "episode.html?trailer=9",
        mp4_link: "T09 - Axl.mp4"      
    },
    {
    	type: "trailer",
        number: 10,
        title: "Merlok 2.0 - Trailer",
        thumbnail: "t10.avif",
        description: "It used to be that old magic did the trick, but no more! An old wizard is using his magic to clean, but nothing is working properly. Plates brake and the wizard is soaked in water. Merlok 2.0 comes in and uses his digital magic and squirebots to make the place spotless and the old wizard dry in minutes. Guess the time has come for Nexo power!",
        metadata: "1m · Oct 15, 2015",
        scheme_metadata: "duration=PT36S|download=T10 - Merlok 2.0.mp4",
        video_data: ["720p", "English", "None"],        
        capture_time: "0:06",  
        link: "episode.html?trailer=10",
        mp4_link: "T10 - Merlok 2.0.mp4"      
    },   
     {
    	type: "trailer",
        number: 11,
        title: "Jestro - Trailer",
        thumbnail: "t11.avif",
        description: "Jestro, the clumsy jester, performs at the royal court. Juggling all sorts of things. Even a smartphone?! Suddenly, the first time in a long, long time, Jestro finally gets a laugh out of the King and Queen. Unfortunately they are not laughing at him, but at something they have seen on their tablets. Jestro withdraws to the shadows and starts plotting for revenge.",
        metadata: "1m · Oct 15, 2015",
        scheme_metadata: "duration=PT36S|download=T11 - Jestro.mp4",
        video_data: ["720p", "English", "None"],        
        capture_time: "0:14",  
        link: "episode.html?trailer=11",
        mp4_link: "T11 - Jestro.mp4"      
    },
     {
    	type: "trailer",
        number: 12,
        title: "Book of Monsters - Trailer",
        thumbnail: "t12.avif",
        description: "Bedtime stories will never be the same again. Two kids are going to bed and their mother is about to read them a story. She reaches for their storybook, but suddenly it grows a mouth and bites her. It is the terrible Book of Monsters. The woman and the kids scream and run off. The Book of Monsters does what it does best; produce monsters.",
        metadata: "1m · Oct 15, 2015",
        scheme_metadata: "duration=PT36S|download=T12 - Book of Monsters.mp4",
        video_data: ["720p", "English", "None"],        
        capture_time: "0:01",  
        link: "episode.html?trailer=12",
        mp4_link: "T12 - Book of Monsters.mp4"
    },

    
    // Minisodes
    /*
  {
    type: "minisode",
    number: 1,
    title: "Knights of the Realm, Pt. 1",
    thumbnail: "m01.avif",
    description: "Jestro's invasion threatens Glockenspiel, forcing the Nexo Knights to fight without Nexo powers, as the Clay's memory sends him back to the Knights' pasts—Macy's royal struggles, Aaron's endless pranks, Lance's lazy routines, Axl's dinner arguments, and Clay's rise from the Hood.",
    metadata: "22m · 2015",
    rating: "8.2",
    video_data: ["1080p, 720p, 360p", "English", "English"],
    capture_time: "10:11",
    link: "episode.html?minisode=1"
  },
  {
    type: "minisode",
    number: 2,
    title: "Knights of the Realm, Pt. 2",
    thumbnail: "vlc_20260108_140527.avif",
    description: "As Ava tries to develop a new Nexo Power, the Knights remember their academy days, where they all meet together, Clay's intense training and Lance's lack of acceptance, Jestro's glow-up from rejected student to Royal Jester.",
    metadata: "22m · 2015",
    rating: "8.1",
    video_data: ["1080p, 720p, 360p", "English", "English"],
    capture_time: "16:14",
    link: "episode.html?minisode=2"
  },*/
    // Webisodes
    {
        type: "webisode",
        number: 1,
        title: "Alliance of the Fortrex",
        thumbnail: "w01.avif",
        description: "The knights arrive to save a village under early morning monster attack. The knights are pushed back by the many evil creatures, but Merlok 2.0 sends them NEXO Powers. With the upgrade the knights defeat the monsters and back in Knightonia King Halbert tries to read them a boring speech. Luckily the knights are called out to save another village.",
        metadata: "5m · Nov 27, 2015",
        scheme_metadata: "duration=PT5M|download=W01 - Alliance of the Fortrex.mp4",
        video_data: ["1080p", "English", "None"],
        capture_time: "0:44",
        link: "episode.html?webisode=1",
        mp4_link: "W01 - Alliance of the Fortrex.mp4"
    },
    {
        type: "webisode",
        number: 2,
        title: "Jestro the Bad... the Really, Really Bad",
        thumbnail: "w02.avif",
        description: "After yet another defeat Jestro thinks back on his life and all he did before he became bad. We see him try to be a wizard, a knight and, of course, a jester. The Book of Monsters starts training Jestro in evil and they attack a village. The knights arrive to fight and soon have Jestro and the Book of Monsters on the run.",
        metadata: "5m · Dec 29, 2015",
        scheme_metadata: "duration=PT5M01S|download=W02 - Jestro the Bad… the Really, Really Bad.mp4",
        video_data: ["1080p", "English", "None"],
        capture_time: "2:56",
        link: "episode.html?webisode=2",
        mp4_link: "W02 - Jestro the Bad… the Really, Really Bad.mp4"
    },
    {
        type: "webisode",
        number: 3,
        title: "Good Knight Clay Moorington!",
        thumbnail: "w03.avif",
        description: "Clay takes a walk in the forest. Monsters follow him. He thinks back to when he was young and started dreaming of becoming a knight and did his first heroic act. The monsters attack him, but he thwarts their attack and defeats them easily. Macy and Aaron are mad he got in a fight without them.",
        metadata: "4m · Dec 29, 2015",
        scheme_metadata: "duration=PT4M03S|download=W03 - Good Knight Clay Moorington!.mp4",
        video_data: ["1080p", "English", "None"],
        capture_time: "1:11",
        link: "episode.html?webisode=3",
        mp4_link: "W03 - Good Knight Clay Moorington!.mp4"
    },
    {
        type: "webisode",
        number: 4,
        title: "Lucky to be Lance",
        thumbnail: "w04.avif",
        description: "Lance is going to a movie premiere with the King and Queen and Lavaria is also sneaking around. Clay calls from a battle and Lance must run off to help him and the other NEXO KNIGHTS heroes. Mid-battle Lance realises that it is a trick to lure him away from the King and Queen and he returns to the premiere just in time to save the day.",
        metadata: "4m · Jan 5, 2016",
        scheme_metadata: "duration=PT4M02S|download=W04 - Lucky to be Lance.mp4",
        video_data: ["1080p", "English", "None"],
        capture_time: "2:00",
        link: "episode.html?webisode=4",
        mp4_link: "W04 - Lucky to be Lance.mp4"
    },
    {
        type: "webisode",
        number: 5,
        title: "Sir Axl... the Ever-Hungry",
        thumbnail: "w05.avif",
        description: "The knights are getting ready to eat, but the monsters have infiltrated the Fortrex kitchen and attack. The knights start fighting them, but Axl just keeps eating. Until they destroy his food. Axl gets an upgrade from Merlok 2.0 and launches himself on a food fight rampage. When he is done he demands dessert.",
        metadata: "4m · Jan 5, 2016",
        scheme_metadata: "duration=PT4M03S|download=W05 - Sir Axl… the Ever-Hungry.mp4",
        video_data: ["1080p", "English", "None"],
        capture_time: "3:19",
        link: "episode.html?webisode=5",
        mp4_link: "W05 - Sir Axl… the Ever-Hungry.mp4"
    },
    {
        type: "webisode",
        number: 6,
        title: "Joust Game on Aaron!",
        thumbnail: "w06.avif",
        description: "Aaron is at the Joust Games and has to do a perfect 10 run in under a minute to win. But in the middle of his run the monsters attack. Aaron powers up on Nexo power and defeats them, but comes in at over a minute. Luckily the judges give him unprecedented 11s and Aaron triumphs again.",
        metadata: "4m · Jan 12, 2016",
        scheme_metadata: "duration=PT4M01S|download=W06 - Joust Game on Aaron!.mp4",
        video_data: ["1080p", "English", "None"],
        capture_time: "1:06",
        link: "episode.html?webisode=6",
        mp4_link: "W06 - Joust Game on Aaron!.mp4"
    },
    {
        type: "webisode",
        number: 7,
        title: "Macy's Parade",
        thumbnail: "w07.avif",
        description: "Macy tests a new floating camera Ava invented and uses it to make a video blog about her life. She trains with her punching bag, promises her mom to behave at the royal ball later and almost helps Chef Eclair, but is called off to battle. She successfully fights Lavaria, but has to run off to get to the gala where she arrives in a royal mess.",
        metadata: "4m · Jan 19, 2016",
        scheme_metadata: "duration=PT4M03S|download=W07 - Macy's Parade.mp4",
        video_data: ["1080p", "English", "None"],
        capture_time: "2:24",
        link: "episode.html?webisode=7",
        mp4_link: "W07 - Macy's Parade.mp4"
    },
    {
        type: "webisode",
        number: 8,
        title: "Brave and Bold (and Short) Sir Robin",
        thumbnail: "w08.avif",
        description: "Robin wants to join the NEXO KNIGHTS heroes in battle, but he is too small. Robin starts developing extra legs to make him taller and ends up developing the powerful Ultra Armor. The knights use the ultra armor to defeat the monsters even more easily than before. All cheer Robin's great idea.",
        metadata: "4m · Jan 26, 2016",
        scheme_metadata: "duration=PT4M02S|download=W08 - Brave and Bold (and Short) Sir Robin.mp4",
        video_data: ["1080p", "English", "None"],
        capture_time: "2:06",
        link: "episode.html?webisode=8",
        mp4_link: "W08 - Brave and Bold (and Short) Sir Robin.mp4"
    },/*

    // minimovies
    {
        type: "minimovie",
        number: 1,
        title: "Champion of Chivalry",
        thumbnail: "mv01.avif",
        description: "Lance is annoyed that people think Clay is more chivalrous than him, so he goes off to train himself in the values of a knight. He kind of succeeds through the Nexo Power Champion of Chivalry, but also demonstrates his complete lack of understanding of the whole thing. Besides the part about the shiny armor that is.",
        metadata: "1m · Mar 17, 2016",
        scheme_metadata: "duration=PT1M03S|download=MV01 - Champion of Chivalry.mp4",
        video_data: ["720p", "English", "None"],
        capture_time: "0:55",
        link: "episode.html?minimovie=1",
        mp4_link: "MV01 - Champion of Chivalry.mp4"
    },
    {
        type: "minimovie",
        number: 2,
        title: "Remote Control",
        thumbnail: "mv02.avif",
        description: "Aaron is searching for his shield while Macy moans about him for always making a mess. Two scurriers have stolen the shield, but through the Nexo Power Remote Control, Merlok 2.0 beat them both up and brings the shield back to the Fortrex.",
        metadata: "1m · Dec 14, 2016",
        scheme_metadata: "duration=PT1M03S|download=MV02 - Remote Control.mp4",
        video_data: ["720p", "English", "None"],
        capture_time: "0:42",
        link: "episode.html?minimovie=2",
        mp4_link: "MV02 - Remote Control.mp4"
    },
    {
        type: "minimovie",
        number: 3,
        title: "Royal Brawl",
        thumbnail: "mv03.avif",
        description: "Jestro and his monsters are attacking a village and KNN are there to cover it. For a short while Macy is in trouble, but then she gets the Royal Brawl! upgrade and beats up the monsters. It is the first time ever a Nexo Power upgrade has been caught on camera and Herb Herbertson is excited.",
        metadata: "1m · Jun 27, 2016",
        scheme_metadata: "duration=PT1M03S|download=MV03 - Royal Brawl.mp4",
        video_data: ["720p", "English", "None"],
        capture_time: "0:16",
        link: "episode.html?minimovie=3",
        mp4_link: "MV03 - Royal Brawl.mp4"
    },
    {
        type: "minimovie",
        number: 4,
        title: "Broom of Doom",
        thumbnail: "mv04.avif",
        description: "Clay wants to train in the Holo-gym, but it is on the fritz and in total chaos. Merlok 2.0 calls on the Nexo Power Broom of Doom and cleans the whole place up in just a second.",
        metadata: "1m · Apr 21, 2016",
        scheme_metadata: "duration=PT1M03S|download=MV04 - Broom of Doom.mp4",
        video_data: ["720p", "English", "None"],
        capture_time: "0:10",
        link: "episode.html?minimovie=4",
        mp4_link: "MV04 - Broom of Doom.mp4"
    },
    {
        type: "minimovie",
        number: 5,
        title: "Rock'n'Roll",
        thumbnail: "mv05.avif",
        description: "Axl has ended up in a labyrinth and the only aid he has is his lute. He is attacked by rock monsters and the action really begins. Axl must summon the NEXO power \"Rock'n'Roll\" and blow his opponents away with the sounds of his lute!",
        metadata: "1m · Dec 25, 2016",
        scheme_metadata: "duration=PT1M03S|download=MV05 - Rock'n'Roll.mp4",
        video_data: ["720p", "German", "None"],
        capture_time: "0:18",
        link: "episode.html?minimovie=5",
        mp4_link: "MV05 - Rock'n'Roll.mp4"
    },
    {
        type: "minimovie",
        number: 6,
        title: "Transformation",
        thumbnail: "mv06.avif",
        description: "Jestro and the Book of Monsters are annoyed that the knights keep defeating them with their NEXO Powers. So they decide to create powers of their own. They send Scurriers out there to steal the ingredients. In the end, they mix everything together and drink the potion. Will it turn out well?",
        metadata: "1m · Dec 17, 2016",
        scheme_metadata: "duration=PT1M03S|download=MV06 - Transformation.mp4",
        video_data: ["720p", "English", "None"],
        capture_time: "0:35",
        link: "episode.html?minimovie=6",
        mp4_link: "MV06 - Transformation.mp4"
    },
    {
        type: "minimovie",
        number: 7,
        title: "Fire Flies",
        thumbnail: "mv07.avif",
        description: "Lost in the woods during an academy field trip, Robin wanders through and comes across Whiparella. The monster chases after the junior knight, snapping her whips at him, until he summons the Nexo Power of Fire Flies. Using his robot legs, he shrinks Whiparella with the power, and she flees.",
        metadata: "1m · Nov 29, 2016",
        scheme_metadata: "duration=PT1M03S|download=MV07 - Fire Flies.mp4",
        video_data: ["720p", "English", "None"],
        capture_time: "0:27",
        link: "episode.html?minimovie=7",
        mp4_link: "MV07 - Fire Flies.mp4"
    },
    {
        type: "minimovie",
        number: 8,
        title: "Star Fall",
        thumbnail: "mv08.avif",
        description: "Lance is having trouble on the set of his latest film ‘Star Fall’ nexo Knights he plays a knight in space. Nothing makes sense and the set and costumes are terrible. Finally Lance gets enough, upgrades with Nexo power ‘Star Fall’ and wraps everything up perfectly.",
        metadata: "1m · Jun 30, 2016",
        scheme_metadata: "duration=PT1M03S|download=MV08 - Star Fall.mp4",
        video_data: ["720p", "English", "None"],
        capture_time: "0:18",
        link: "episode.html?minimovie=8",
        mp4_link: "MV08 - Star Fall.mp4"
    },
    {
        type: "minimovie",
        number: 9,
        title: "Force of Nature",
        thumbnail: "mv09.avif",
        description: 'Macy walks in the forest and observes the cute little bunnies. She is attacked by Lavaria, Moltor and Flama, who want to deliver her to Jestro. Macy fights them, then uses the NEXO power "Force of Nature". She directs power not to herself, but to the rabbits, who suddenly transform into odious beasties that hunt monsters.',
        metadata: "1m · Nov 21, 2016",
        scheme_metadata: "duration=PT1M03S|download=MV09 - Force of Nature.mp4",
        video_data: ["720p", "French", "None"],
        capture_time: "0:13",
        link: "episode.html?minimovie=9",
        mp4_link: "MV09 - Force of Nature.mp4"
    },
    {
        type: "minimovie",
        number: 10,
        title: "Shark Attack",
        thumbnail: "mv10.avif",
        description: "In the middle of a pie-eating record attempt Axl is attacked by monsters. While defending the innocent he upgrades with the Shark Attack Nexo power and finishes both the monsters and his pile of pies just in time.",
        metadata: "1m · May 2, 2016",
        scheme_metadata: "duration=PT1M03S|download=MV10 - Shark Attack.mp4",
        video_data: ["720p", "English", "None"],
        capture_time: "0:18",
        link: "episode.html?minimovie=10",
        mp4_link: "MV10 - Shark Attack.mp4"
    },
    {
        type: "minimovie",
        number: 11,
        title: "Tale Of The Nexo Powers",
        thumbnail: "mv11.avif",
        description: "Ava and Merlok 2.0 are trying to get all the NEXO Powers organized, but it is proving difficult. Merlok tells a story about the old kind of magic he used to practice, but Ava pulls him back to reality and shows him how the new kind of NEXO Powers that upgrade the NEXO KNIGHTS heroes and help them defeat Jestro are much, much cooler.",
        metadata: "2m · May 30, 2016",
        scheme_metadata: "duration=PT2M03S|download=MV11 - Tale Of The Nexo Powers.mp4",
        video_data: ["720p", "English", "None"],
        capture_time: "0:52",
        link: "episode.html?minimovie=11",
        mp4_link: "MV11 - Tale Of The Nexo Powers.mp4"
    },
    {
        type: "minimovie",
        number: 12,
        title: "Quick Sand",
        thumbnail: "mv12.avif",
        description: "The NEXO KNIGHTS heroes are in trouble. They are fighting a horde of monsters in a little town and Merlok 2.0 is fighting his interface, unable to send them a NEXO Power. Ava steps up. She reboots Merlok 2.0’s system and sends the NEXO KNIGHTS heroes a power at the same time.",
        metadata: "1m · Aug 6, 2016",
        scheme_metadata: "duration=PT1M03S|download=MV12 - Quick Sand.mp4",
        video_data: ["720p", "English", "None"],
        capture_time: "0:40",
        link: "episode.html?minimovie=12",
        mp4_link: "MV12 - Quick Sand.mp4"
    },
    {
        type: "minimovie",
        number: 13,
        title: "Snake Den",
        thumbnail: "mv13.avif",
        description: "Clay is fighting snakes in the Fortrex training room and realizes that he is scared of them. He talks to Robin and Merlok about his fears and gets an idea. Back in the training room Clay has learned to use his fears as a weapon against the monsters.",
        metadata: "1m · Aug 24, 2016",
        scheme_metadata: "duration=PT1M03S|download=MV13 - Snake Den.mp4",
        video_data: ["720p", "English", "None"],
        capture_time: "0:49",
        link: "episode.html?minimovie=13",
        mp4_link: "MV13 - Snake Den.mp4"
    },
    {
        type: "minimovie",
        number: 14,
        title: "Always Prepared",
        thumbnail: "mv14.avif",
        description: "What’s going on? Have the squire bots developed fantastic new powers? Or have they invented some genius device to battle the monsters? There's something fishy going on here - and it’s not coming from Chef Eclairs kitchen!",
        metadata: "2m · Dec 15, 2016",
        scheme_metadata: "duration=PT2M|download=MV14 - Always Prepared.mp4",
        video_data: ["720p", "English", "None"],
        capture_time: "1:24",
        link: "episode.html?minimovie=14",
        mp4_link: "MV14 - Always Prepared.mp4"
    }*/
];

export const episodeData = [
    {
        type: "episode",
        number: 1,
        title: "The Book of Monsters, Pt. 1",
        thumbnail: "e01.avif",
        description: "When Jestro the Jester finds the Book of Monsters, chaos breaks loose in the Kingdom of Knighton. Can the newly graduated Knights from the Knights' Academy save the kingdom?",
        metadata: "22m · Dec 13, 2015",
        scheme_metadata: "duration=PT22M|download=E01 - The Book of Monsters, Pt. 1.mp4", 
        rating: "7.3",
        video_data: ["720p", "default", "English"],
        capture_time: "18:28",
        link: "episode.html?episode=1",
        m3u8_link: "episodes/e01/e01__main.m3u8"
    },
    {
        type: "episode",
        number: 2,
        title: "The Book of Monsters, Pt. 2",
        thumbnail: "e02.avif",
        description: "Realizing they must defend the Kingdom from Jestro's monsters, the Knights are despondent when they discover their advisor – Merlok the Magician – has sacrificed himself to save them.",
        metadata: "22m · Dec 13, 2015",
        scheme_metadata: "duration=PT22M|download=E02 - The Book of Monsters, Pt. 2.mp4", 
        rating: "7.6",
        video_data: ["720p", "default", "English"],
        capture_time: "10:29",
        link: "episode.html?episode=2",
        m3u8_link: "episodes/e02/e02__main.m3u8"
    },
    {
        type: "episode",
        number: 3,
        title: "The Power of Merlok",
        thumbnail: "e03.avif",
        description: 'When Jestro attacks a village, the Nexo Knights wonder how they\'ll get there. Macy remembers her dad has a royal RV that can be "modded" for their own, "knightly" use?',
        metadata: "22m · Jan 13, 2016",
        scheme_metadata: "duration=PT22M|download=E03 - The Power of Merlok.mp4", 
        rating: "7.0",
        video_data: ["720p", "default", "English"],
        capture_time: "12:46",
        link: "episode.html?episode=3",
        m3u8_link: "episodes/e03/e03__main.m3u8"
    },
    {
        type: "episode",
        number: 4,
        title: "The Knight's Code",
        thumbnail: "e04.avif",
        description: "Jestro uses the Book of Chaos to unleash, um, chaos and attack the King's hover train to try and kidnap the royal party. Can the NEXO-Knights bring order out of the chaos and save the King?",
        metadata: "22m · Jan 14, 2016",
        scheme_metadata: "duration=PT22M|download=E04 - The Knight's Code.mp4",
        rating: "6.8",
        video_data: ["720p", "default", "English"],
        capture_time: "1:28",
        link: "episode.html?episode=4",
        m3u8_link: "episodes/e04/e04__main.m3u8"
    },
    {
        type: "episode",
        number: 5,
        title: "Fright Knight",
        thumbnail: "e05.avif",
        description: "Using the Book of Fear, Jestro calls forth Whipperella and uses her to trap the knights in the dark woods where they realize their darkest fears.",
        metadata: "22m · Jan 15, 2016",
        scheme_metadata: "duration=PT22M|download=E05 - Fright Knight.mp4",
        rating: "7.1",
        video_data: ["720p", "default", "English"],
        capture_time: "12:05",
        link: "episode.html?episode=5",
        m3u8_link: "episodes/e05/e05__main.m3u8"
    },
    {
        type: "episode",
        number: 6,
        title: "The Golden Castle",
        thumbnail: "e06.avif",
        description: 'When Lance is cast as the star in the new remake of "Ned Knightly and the Golden Castle", he doesn\'t anticipate Jestro and his monsters invading the set and ruining his starring role.',
        metadata: "22m · Mar 3, 2016",
        scheme_metadata: "duration=PT22M|download=E06 - The Golden Castle.mp4",
        rating: "6.4",
        video_data: ["720p", "default", "English"],
        capture_time: "2:08",
        link: "episode.html?episode=6",
        m3u8_link: "episodes/e06/e06__main.m3u8"
    },
    {
        type: "episode",
        number: 7,
        title: "The Maze of Amazement",
        thumbnail: "e07.avif",
        description: "The Knights find themselves trapped in a maze looking for the Book of Deception. But will they actually get their hands on it, or will it keep deceiving them?",
        metadata: "22m · Mar 10, 2016",
        scheme_metadata: "duration=PT22M|download=E07 - The Maze of Amazement.mp4",
        rating: "6.5",
        video_data: ["720p", "default", "English"],
        capture_time: "13:11",
        link: "episode.html?episode=7",
        m3u8_link: "episodes/e07/e07__main.m3u8"
    },
    {
        type: "episode",
        number: 8,
        title: "The Black Knight",
        thumbnail: "e08.avif",
        description: "It seems the Nexo Knights are attacking villages throughout the realm! But why? A mysterious Black Knight appears to defend the cities from the rogue NEXO-villains!",
        metadata: "22m · Mar 17, 2016",
        scheme_metadata: "duration=PT22M|download=E08 - The Black Knight.mp4",
        rating: "6.5",
        video_data: ["720p", "default", "English"],
        capture_time: "9:24",
        link: "episode.html?episode=8",
        m3u8_link: "episodes/e08/e08__main.m3u8"
    },
    {
        type: "episode",
        number: 9,
        title: "The Book of Total Badness",
        thumbnail: "e09.avif",
        description: "The NEXO-Knights must fight Jestro's Monsters of Destruction which are attacking all over the Kingdom. But Merlok smells a trap. Is he right?",
        metadata: "22m · Mar 24, 2016",
        scheme_metadata: "duration=PT22M|download=E09 - The Book of Total Badness.mp4",
        rating: "7.1",
        video_data: ["720p", "default", "English"],
        capture_time: "13:21",
        link: "episode.html?episode=9",
        m3u8_link: "episodes/e09/e09__main.m3u8"
    },
    {
        type: "episode",
        number: 10,
        title: "The Might and the Magic",
        thumbnail: "e10.avif",
        description: "Aaron races to gather the NEXO-Knights as Jestro and his Destructive Monsters attack the King's Castle. The Knights must get back to the capitol in time, or Jestro will rule the kingdom!",
        metadata: "22m · Mar 24, 2016",
        scheme_metadata: "duration=PT22M|download=E10 - The Might and the Magic.mp4",
        rating: "7.1",
        video_data: ["720p", "default", "English"],
        capture_time: "15:37",
        link: "episode.html?episode=10",
        m3u8_link: "episodes/e10/e10__main.m3u8"
    },
    {
        "type": "episode",
        "number": 11,
        "title": "Back to School",
        "thumbnail": "soon.avif",
        "description": "When the Nexo Knights are sloppy in a fight with Jestro, Merlok 2.0 sends them back to the Knights' Academy for a brush-up and to find out what Jestro is after in its hallowed halls.",
        "metadata": "22m · Jul 24, 2016",
        "rating": "7.0",
        "video_data": ["720p", "default", "English"],
        "capture_time": "19:21",
        "link": "episode.html?episode=11",
        //"m3u8_link": "episodes/e11/e11__main.m3u8"
    },
    {
        "type": "episode",
        "number": 12,
        "title": "Greed is Good?",
        "thumbnail": "soon.avif",
        "description": "When Jestro uses the Book of Greed to rob Auremville of its riches, he also gets Lance's parents as prisoners and these demanding rich folks are too much for even monsters to handle.",
        "metadata": "22m · Aug 13, 2016",
        "rating": "7.0",
        "video_data": ["720p", "default", "English"],
        "capture_time": "12:31",
        "link": "episode.html?episode=12",
        //"m3u8_link": "episodes/e12/e12__main.m3u8"
    },
    {
        "type": "episode",
        "number": 13,
        "title": "The Book of Obsession",
        "thumbnail": "soon.avif",
        "description": "The knights are tasked with protecting the King's valuable Ned Knights comic book during the Bookingheim Knight-a-Kon. But with all the costumed kids there, will they recognise the real Jestro and Book of Monsters coming to get them?",
        "metadata": "22m · Aug 13, 2016",
        "rating": "6.3",
        "video_data": ["720p", "default", "English"],
        "capture_time": "20:40",
        "link": "episode.html?episode=13",
        //"m3u8_link": "episodes/e13/e13__main.m3u8"
    },
    {
        "type": "episode",
        "number": 14,
        "title": "The King's Tournament",
        "thumbnail": "soon.avif",
        "description": "Rival to the King, Jorah Tightwad thinks his knights - the Tighty Knighties - are easily better than the NEXO KNIGHTS, so he challenges King Halbert to prove who's better during the King's Birthday Tournament.",
        "metadata": "22m · Sep 10, 2016",
        "rating": "6.8",
        "video_data": ["720p", "default", "English"],
        "capture_time": "4:41",
        "link": "episode.html?episode=14",
        //"m3u8_link": "episodes/e14/e14__main.m3u8"
    },
    {
        "type": "episode",
        "number": 15,
        "title": "Monster Chef",
        "thumbnail": "soon.avif",
        "description": "Axl and Chef Éclair must enter a cooking contest to keep Jestro from getting the hottest chili recipe in the realm.",
        "metadata": "22m · Sep 17, 2016",
        "rating": "6.9",
        "video_data": ["720p", "default", "English"],
        "capture_time": "7:19",
        "link": "episode.html?episode=15",
        //"m3u8_link": "episodes/e15/e15__main.m3u8"
    },
    {
        "type": "episode",
        "number": 16,
        "title": "Knight Out",
        "thumbnail": "soon.avif",
        "description": "When the other NEXO KNIGHTS decide they need a vacation from Clay, they send him on a holiday not knowing that he's going to a resort that houses an evil book or that Jestro would be heading there too.",
        "metadata": "22m · Sep 24, 2016",
        "rating": "7.4",
        "video_data": ["720p", "default", "English"],
        "capture_time": "12:58",
        "link": "episode.html?episode=16",
        //"m3u8_link": "episodes/e16/e16__main.m3u8"
    },
    {
        "type": "episode",
        "number": 17,
        "title": "Saturday Knight Fever",
        "thumbnail": "soon.avif",
        "description": "The Book of Monsters catching a cold means trouble for the NEXO KNIGHTS when he can create an entirely new kind of \"snotty\" monster.",
        "metadata": "22m · Oct 1, 2016",
        "rating": "6.5",
        "video_data": ["720p", "default", "English"],
        "capture_time": "6:13",
        "link": "episode.html?episode=17",
        //"m3u8_link": "episodes/e17/e17__main.m3u8"
    },
    {
        "type": "episode",
        "number": 18,
        "title": "Open Mike Knight",
        "thumbnail": "soon.avif",
        "description": "The Book of Betrayal leads Jestro and his Monsters to Funnyton - the funniest town in the kingdom. When the Knights arrive to capture him, they discover (to their shock) that Jestro and the Book of Monsters are now the town's top comedians!",
        "metadata": "22m · Oct 8, 2016",
        "rating": "7.6",
        "video_data": ["720p", "default", "English"],
        "capture_time": "5:39",
        "link": "episode.html?episode=18",
        //"m3u8_link": "episodes/e18/e18__main.m3u8"
    },
    {
        "type": "episode",
        "number": 19,
        "title": "The Fortrex and the Furious",
        "thumbnail": "soon.avif",
        "description": "In a massive chase around Knighton, the Nexo Knights attempt to keep the Book of Betrayal out of the Book of Monsters' grip. But the evil book is persistent. Will he get the final piece of his evil puzzle?",
        "metadata": "22m · Oct 15, 2016",
        "rating": "7.1",
        "video_data": ["720p", "default", "English"],
        "capture_time": "21:15",
        "link": "episode.html?episode=19",
        //"m3u8_link": "episodes/e19/e19__main.m3u8"
    },
    {
        "type": "episode",
        "number": 20,
        "title": "Kingdom of Heroes",
        "thumbnail": "soon.avif",
        "description": "The Book of Monsters, having the final pieces of his evil plan in place, tries to take human form. Can the NEXO KNIGHTS and Merlok 2.0 stop the greatest threat they've ever faced? Or will the kingdom be plunged into darkness... forever.",
        "metadata": "22m · Oct 22, 2016",
        "rating": "7.9",
        "video_data": ["720p", "default", "English"],
        "capture_time": "1:30",
        "link": "episode.html?episode=20",
        "m3u8_link": "episodes/e20/e20__main.m3u8"
    },
  {
    type: "episode",
    number: 21,
    title: "The Cloud",
    thumbnail: "soon.avif",
    description: "A storm is brewing over Knighton. Monstrox has taken the form of a cloud and is raising an army of lightning infused Stone Monsters. His first target is the new Lavalands Amusement Park.",
    metadata: "22m · Feb 4, 2017",
    rating: "7.0",
    video_data: ["720p", "non-default", "English"],
    capture_time: "9:38",
    link: "episode.html?episode=21"
  },
  {
    type: "episode",
    number: 22,
    title: "A Little Rusty",
    thumbnail: "soon.avif",
    description: "The Cloud of Monstrox and Jestro unlock a mysterious Forbidden Power. What kind of havoc will they unleash? And can Merlok 2.0 and the NEXO KNIGHTS make the new COMBO NEXO Powers work?",
    metadata: "22m · Feb 11, 2017",
    rating: "6.5",
    video_data: ["720p", "non-default", "English"],
    capture_time: "4:44",
    link: "episode.html?episode=22"
  },
  {
    type: "episode",
    number: 23,
    title: "Mount Thunderstrox",
    thumbnail: "soon.avif",
    description: "Jestro and the Cloud of Monstrox encounters the sculptor. He helps unleash a horde of fierce garden gnomes on Knighton. What will the NEXO KNIGHTS do against this new enemy? Will their new COMBO NEXO Powers do the trick?",
    metadata: "22m · Feb 18, 2017",
    rating: "7.1",
    video_data: ["720p", "non-default", "English"],
    capture_time: "5:06",
    link: "episode.html?episode=23"
  },
  {
    type: "episode",
    number: 24,
    title: "Rotten Luck",
    thumbnail: "soon.avif",
    description: "Jestro and the Cloud of Monstrox unleashes the Forbidden Power Ravaging Rot on Knighton, turning everything into green gooey rot. But Robin has an awesome new invention that could help the NEXO KNIGHTS.",
    metadata: "22m · Feb 25, 2017",
    rating: "7.3",
    video_data: ["720p", "non-default", "English"],
    capture_time: "13:04",
    link: "episode.html?episode=24"
  },
  {
    type: "episode",
    number: 25,
    title: "Storm Over Rock Wood",
    thumbnail: "soon.avif",
    description: "The NEXO KNIGHTS have their powerful shields stolen by Robot Hoodlum and his Merry Mechs. And something is coming to life in the Petrified forest, and it doesn't like the knights. Can the NEXO KNIGHTS deal with this without their shields?",
    metadata: "22m · Mar 4, 2017",
    rating: "7.2",
    video_data: ["720p", "non-default", "English"],
    capture_time: "1:13",
    link: "episode.html?episode=25"
  },
  {
    type: "episode",
    number: 26,
    title: "Miner Setback",
    thumbnail: "soon.avif",
    description: "Villagers are being enslaved to dig out three ancient warriors whom the Cloud of Monstrox wants to bring back to life. Can the NEXO KNIGHTS make their COMBO NEXO POWERS work inside a mountain?",
    metadata: "22m · Mar 11, 2017",
    rating: "6.9",
    video_data: ["720p", "non-default", "English"],
    capture_time: "11:18",
    link: "episode.html?episode=26"
  },
  {
    type: "episode",
    number: 27,
    title: "Knight at the Museum",
    thumbnail: "soon.avif",
    description: "At K.O.M.A (Knightonia Official Museum of Art) Monstrox learns that a Forbidden Power tablet is hidden, and he will do anything to get it. Especially if King Halbert happens to visit at the same time. The NEXO KNIGHTS must save all!",
    metadata: "22m · Mar 18, 2017",
    rating: "7.8",
    video_data: ["720p", "non-default", "English"],
    capture_time: "8:52",
    link: "episode.html?episode=27"
  },
  {
    type: "episode",
    number: 28,
    title: "Hot Rock Massage",
    thumbnail: "soon.avif",
    description: "The old Lava Monsters are back! And a new Forbidden Power is in the middle of their new village of Burningham. But whose side are the Lava Monsters on?",
    metadata: "22m · Mar 25, 2017",
    rating: "7.9",
    video_data: ["720p", "non-default", "English"],
    capture_time: "9:30",
    link: "episode.html?episode=28"
  },
  {
    type: "episode",
    number: 29,
    title: "Rock Bottom",
    thumbnail: "soon.avif",
    description: "Macy is mad! The three Harpies have kidnapped her mom Queen Halbert. The Nexo Knights use everything in their power to rescue her. But is kidnapping the real plan or is the Cloud of Monstrox after something else?",
    metadata: "22m · Apr 8, 2017",
    rating: "8.4",
    video_data: ["720p", "non-default", "English"],
    capture_time: "6:26",
    link: "episode.html?episode=29"
  },
  {
    type: "episode",
    number: 30,
    title: "In Charge",
    thumbnail: "soon.avif",
    description: "The Cloud of Monstrox is growing more and more powerful with every Forbidden Power Jestro inserts. The capital of Knighton is under attack. The Fortrex is damaged and Clay is turned to stone. Dark clouds are truly gathering over the realm.",
    metadata: "22m · Apr 8, 2017",
    rating: "7.9",
    video_data: ["720p", "non-default", "English"],
    capture_time: "12:47",
    link: "episode.html?episode=30"
  },
  {
    type: "episode",
    number: 31,
    title: "Weekend at Halbert's",
    thumbnail: "soon.avif",
    description: "Party time in Knighton! The mood is down so the King decides to throw a party. In the meantime, Jestro attacks the Fortrex, but he is confronted with the new NEXO Power \"The Wedgie of Doom\".",
    metadata: "22m · Aug 21, 2017",
    rating: "6.7",
    video_data: ["720p", "non-default", "English"],
    capture_time: "1:43",
    link: "episode.html?episode=31"
  },
  {
    type: "episode",
    number: 32,
    title: "The Gray Knight",
    thumbnail: "soon.avif",
    description: "The Cloud of Monstrox turns Clay into a living, fighting, breathing stone fighting knight. But will Clay use his forces to fight for good or for evil? Does he have a choice?",
    metadata: "22m · Aug 22, 2017",
    rating: "8.0",
    video_data: ["720p", "non-default", "English"],
    capture_time: "13:11",
    link: "episode.html?episode=32"
  },
  {
    type: "episode",
    number: 33,
    title: "The Good, the Bad and the Tightwad",
    thumbnail: "soon.avif",
    description: "Clay wakes up in the poor town of Nothing Hill which literally has nothing. Will Clay remember who he is and what he is fighting for? His friends try to help him, but Jorah Tightwad and his Bots get in the way.",
    metadata: "22m · Aug 23, 2017",
    rating: "8.4",
    video_data: ["720p", "non-default", "English"],
    capture_time: "4:24",
    link: "episode.html?episode=33"
  },
  {
    type: "episode",
    number: 34,
    title: "In his Majesty's Secret Service",
    thumbnail: "soon.avif",
    description: "The Nexo Knights decide to use Clay to infiltrate the enemy camp but first Clay needs to learn how to be a good spy. Agent Shield, Jack Shield helps them with that.",
    metadata: "22m · Aug 24, 2017",
    rating: "7.8",
    video_data: ["720p", "non-default", "English"],
    capture_time: "8:30",
    link: "episode.html?episode=34"
  },  
  {
    type: "episode",
    number: 35,
    title: "The Stranger in the Halps",
    thumbnail: "soon.avif",
    description: "Jestro and the Cloud of Monstrox builds a new stone army from giant building blocks to crush Knighton. The NEXO KNIGHTS try to convince Rockowski, a demolition expert, to help them.",
    metadata: "22m · Aug 25, 2017",
    rating: "7.9",
    video_data: ["720p", "non-default", "English"],
    capture_time: "6:28",
    link: "episode.html?episode=35"
  },
  {
    type: "episode",
    number: 36,
    title: "Krakenskull",
    thumbnail: "soon.avif",
    description: "Jorah Tightwad is digging for gold but finds the ancient Lord Krakenskull buried with his army. This stone army is exactly what the Cloud of Monstrox needs.",
    metadata: "22m · Aug 28, 2017",
    rating: "7.8",
    video_data: ["720p", "non-default", "English"],
    capture_time: "7:06",
    link: "episode.html?episode=36"
  },
  {
    type: "episode",
    number: 37,
title: "Heart of Stone",
thumbnail: "soon.avif",
description: "Clay Moorington had enough of Monstrox, Jestro and their Forbidden Powers and decides to take the fight to them. But the Cloud of Monstrox is getting closer and closer to unleash his master plan.",
metadata: "22m · Aug 29, 2017",
rating: "8.6",
video_data: ["720p", "non-default", "English"],
capture_time: "2:04",
link: "episode.html?episode=37"
},
  {
    type: "episode",
    number: 38,
    title: "Between a Rock and a Hard Place",
    thumbnail: "soon.avif",
    description: "Things are getting dire in Knighton. Jestro and the Cloud of Monstrox only need the Forbidden Power of Awesome Annihilation in order to reveal what's hidden in Mount Thunderstrox. It can't be nice.",
    metadata: "22m · Aug 30, 2017",
    rating: "8.2",
    video_data: ["720p", "non-default", "English"],
    capture_time: "9:21",
    link: "episode.html?episode=38"
  },
  {
    type: "episode",
    number: 39,
    title: "March of the Colossus",
    thumbnail: "soon.avif",
    description: "The giant Stone Colossus is marching on Knighton. Ruina the witch tries to get to Clay, but the other NEXO KNIGHTS need him in their final defense of the realm. Which side will he choose? Family or friends?",
    metadata: "22m · Aug 31, 2017",
    rating: "7.9",
    video_data: ["720p", "non-default", "English"],
    capture_time: "6:12",
    link: "episode.html?episode=39"
  },
  {
    type: "episode",
    number: 40,
    title: "The Fall",
    thumbnail: "soon.avif",
    description: "The Cloud of Monstrox is inside of The Stone Colossus and it now stands in front of Knighton. The students of the Knights Academy are mobilized, the King and Queen are on the defence and the NEXO KNIGHTS are ready for the final showdown.",
    metadata: "22m · Sep 1, 2017",
    rating: "8.2",
    video_data: ["720p", "non-default", "English"],
    capture_time: "8:56",
    link: "episode.html?episode=40"
  }
];
